trainer: feed_forward.image_classification.image_classification
model_class: feed_forward.image_classification.manual.n_layer.n_layer_nn.N_Layer_NN
config:
  layers_dims: [12288, 20, 7, 5, 1] #  5-layer model
  learning_rate: 0.0075
  num_iterations: 2000
  print_cost: True
