trainer: feed_forward.image_classification.image_classification
model_class: feed_forward.image_classification.manual.two_layer.two_layer_nn.Two_Layer_NN
config:
  n_x: 12288     # num_px * num_px * 3
  n_h: 7
  n_y: 1
  # layers_dims: (n_x, n_h, n_y)
  learning_rate: 0.008
  num_iterations: 2500
  print_cost: True
